version: '3.8'

services:
  web:
    build: .
    ports:
      - "1212:5000"
    environment:
      - PORT=5000
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
