services:
  web:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - PARCEL_HMR_HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
